"""
This module contains a sample api data mostly
used for testing of app.
"""

api_response_issues = [
  {
    "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/22",
    "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
    "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/22/labels{/name}",
    "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/22/comments",
    "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/22/events",
    "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/22",
    "id": 248006788,
    "number": 22,
    "title": "Implement issue parsing functionality using `isuue-labels`.",
    "user": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [
      {
        "id": 661918134,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Django",
        "name": "Django",
        "color": "006b75",
        "default": False
      },
      {
        "id": 661917194,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/moderate",
        "name": "moderate",
        "color": "fbca04",
        "default": False
      },
      {
        "id": 661917884,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Python",
        "name": "Python",
        "color": "bfdadc",
        "default": False
      }
    ],
    "state": "open",
    "locked": False,
    "assignee": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2017-08-04T13:30:25Z",
    "updated_at": "2017-08-04T13:30:25Z",
    "closed_at": None,
    "body": "Add issue parsing functionality according to labels instead of a template."
  },
  {
    "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/21",
    "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
    "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/21/labels{/name}",
    "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/21/comments",
    "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/21/events",
    "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/pull/21",
    "id": 246583664,
    "number": 21,
    "title": "Feature regions",
    "user": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [

    ],
    "state": "open",
    "locked": False,
    "assignee": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2017-07-30T13:24:59Z",
    "updated_at": "2017-07-30T13:34:56Z",
    "closed_at": None,
    "pull_request": {
      "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/pulls/21",
      "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/pull/21",
      "diff_url": "https://github.com/mozillacampusclubs/issue_parser_backend/pull/21.diff",
      "patch_url": "https://github.com/mozillacampusclubs/issue_parser_backend/pull/21.patch"
    },
    "body": "fix #20 Add regions functionality"
  },
  {
    "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/20",
    "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
    "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/20/labels{/name}",
    "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/20/comments",
    "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/20/events",
    "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/20",
    "id": 244833992,
    "number": 20,
    "title": "Add regions model to add different regions to the system",
    "user": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [
      {
        "id": 661918134,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Django",
        "name": "Django",
        "color": "006b75",
        "default": False
      },
      {
        "id": 613678729,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/enhancement",
        "name": "enhancement",
        "color": "84b6eb",
        "default": True
      },
      {
        "id": 661917194,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/moderate",
        "name": "moderate",
        "color": "fbca04",
        "default": False
      },
      {
        "id": 661917884,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Python",
        "name": "Python",
        "color": "bfdadc",
        "default": False
      }
    ],
    "state": "open",
    "locked": False,
    "assignee": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2017-07-22T08:43:46Z",
    "updated_at": "2017-08-04T13:31:17Z",
    "closed_at": None,
    "body": "Experience: Moderate\r\nExpected-time: 1 week\r\nLanguage: python\r\nTechnology-stack: Django\r\n\r\n## Description\r\nAdd regions model to add different regions to the system"
  },
  {
    "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7",
    "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
    "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/labels{/name}",
    "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/comments",
    "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/events",
    "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/7",
    "id": 233564738,
    "number": 7,
    "title": "Dockerize Project",
    "user": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [
      {
        "id": 661918134,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Django",
        "name": "Django",
        "color": "006b75",
        "default": False
      },
      {
        "id": 661916826,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/easyfix",
        "name": "easyfix",
        "color": "0e8a16",
        "default": False
      },
      {
        "id": 613678729,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/enhancement",
        "name": "enhancement",
        "color": "84b6eb",
        "default": True
      },
      {
        "id": 661917884,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Python",
        "name": "Python",
        "color": "bfdadc",
        "default": False
      }
    ],
    "state": "open",
    "locked": False,
    "assignee": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2017-06-05T11:47:01Z",
    "updated_at": "2017-08-04T13:31:42Z",
    "closed_at": None,
    "body": "Experience: Easyfix\r\nExpected-time: 3 hours\r\nLanguage: Python\r\nTechnology-stack Django\r\n\r\n## Description\r\nDockerize this backend project for development and deployment purposes."
  },
  {
    "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6",
    "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
    "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/labels{/name}",
    "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/comments",
    "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/events",
    "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/6",
    "id": 233429779,
    "number": 6,
    "title": "Implement expected time feature",
    "user": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [
      {
        "id": 661918134,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Django",
        "name": "Django",
        "color": "006b75",
        "default": False
      },
      {
        "id": 613678729,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/enhancement",
        "name": "enhancement",
        "color": "84b6eb",
        "default": True
      },
      {
        "id": 661917884,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/Python",
        "name": "Python",
        "color": "bfdadc",
        "default": False
      },
      {
        "id": 661917366,
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/senior",
        "name": "senior",
        "color": "d93f0b",
        "default": False
      }
    ],
    "state": "open",
    "locked": False,
    "assignee": {
      "login": "razat249",
      "id": 10090911,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/razat249",
      "html_url": "https://github.com/razat249",
      "followers_url": "https://api.github.com/users/razat249/followers",
      "following_url": "https://api.github.com/users/razat249/following{/other_user}",
      "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
      "organizations_url": "https://api.github.com/users/razat249/orgs",
      "repos_url": "https://api.github.com/users/razat249/repos",
      "events_url": "https://api.github.com/users/razat249/events{/privacy}",
      "received_events_url": "https://api.github.com/users/razat249/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars2.githubusercontent.com/u/10090911?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2017-06-04T12:11:53Z",
    "updated_at": "2017-08-04T13:32:49Z",
    "closed_at": None,
    "body": "Experience: Senior\r\nExpected-time: 1 week\r\nLanguage: Python\r\nTechnology-stack Django\r\n\r\n## Description\r\nRight now the expected time is a string field. It should work logically so that we can easily filter issues with different expected time."
  }
]
